- README.md
- package-lock.json
- package.json
Adding installation instructions to `README.md`.
> Provide installation instructions

- .travis.yml
- package-lock.json
- package.json
- packages/cli/src/__snapshots__/cli.spec.js.snap
- packages/cli/src/cli.js
> Add travis-ci and coveralls

- README.md
Adds lovely badges to the readme. everybody has 'em. we need 'em.
> Add travis and codeclimate badges

- packages/storage-events/package.json
- packages/storage-events/src/__tests__/basic.events
- packages/storage-events/src/__tests__/basic.todo
- packages/storage-events/src/storage.js
- packages/storage-events/src/storage.spec.js
Initial work on the `storage-event` module
> Add storage for event sourcing

- packages/storage-events/package-lock.json
- packages/storage-events/src/__snapshots__/storage.spec.js.snap
- packages/storage-events/src/storage.js
- packages/storage-events/src/storage.spec.js
We should merge this and see what events we need in the app itself later.
> More events

- jest.config.js
- packages/dashboard/src/dashboard.js
- packages/storage-file/src/storage.js
Removes some code smells according to code climate.
> Fix some code smells

- .travis.yml
- packages/server-socket/src/command-processor.js
- packages/server-web/src/client/components/Home.vue
- packages/server-web/src/client/components/TodoAdder.vue
- packages/server-web/src/client/components/TodoItem.vue
- packages/server-web/src/client/components/TodoList.vue
- packages/server-web/src/index.html
- packages/server-web/src/main.css
- packages/server-web/src/server.js
We should merge this quickly and create new branches from master again
> Styling and recursive Todos

- packages/storage-events/src/storage.js
- packages/storage-events/src/storage.spec.js
We need to be able to remove child todos as well. Added test and implementation for the event storage
> Add removal of child todos

- packages/server-socket/package.json
- packages/server-socket/src/__snapshots__/command-processor.spec.js.snap
- packages/server-socket/src/command-processor.js
- packages/server-socket/src/command-processor.spec.js
- packages/server-socket/src/server-socket.js
- packages/storage-events/src/__snapshots__/logger.spec.js.snap
- packages/storage-events/src/__snapshots__/replay.spec.js.snap
- packages/storage-events/src/__tests__/tmp-file.log
- packages/storage-events/src/logger.js
- packages/storage-events/src/logger.spec.js
- packages/storage-events/src/replay.js
- packages/storage-events/src/replay.spec.js
- packages/storage-events/src/storage.js
- packages/storage-events/src/storage.spec.js
The server socket now saves and loads from a `todastic.events` file. This should make the server keep all tasks for now. It saves every 5 seconds (we should change that later).
> Load save events

- packages/server-socket/src/command-processor.js
- packages/server-web/src/client/components/TodoAdder.vue
- packages/server-web/src/client/components/TodoItem.vue
- packages/server-web/src/client/components/TodoOptions.vue
- packages/server-web/src/main.css
General styling overhaul, moved options into separate file and put the options inside a hover effect.
> Better styling

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/dashboard/package-lock.json
- packages/dashboard/package.json
- packages/server-socket/__mocks__/uuid.js
- packages/server-socket/package-lock.json
- packages/server-socket/package.json
- packages/server-socket/src/__snapshots__/command-processor.spec.js.snap
- packages/server-socket/src/command-processor.js
- packages/server-socket/src/command-processor.spec.js
- packages/server-web/package-lock.json
- packages/server-web/package.json
- packages/server-web/src/client/components/TodoItem.vue
- packages/storage-events/package-lock.json
- packages/storage-events/package.json
- packages/storage-file/package-lock.json
- packages/storage-file/package.json
If you have a good idea on the TODO in command_processor.js, I'd be happy to learn how it works.
Also: we don't have any sorting right now anywhere, right?
> Add timestamp

- packages/server-socket/src/__snapshots__/command-processor.spec.js.snap
- packages/server-socket/src/command-processor.js
- packages/server-socket/src/command-processor.spec.js
- packages/server-web/src/app.js
- packages/server-web/src/client/components/Home.vue
- packages/server-web/src/client/components/TodoAdder.vue
- packages/server-web/src/client/components/TodoItem.vue
- packages/server-web/src/client/socket-connection.js
- packages/storage-events/src/__snapshots__/replay.spec.js.snap
- packages/storage-events/src/replay.js
- packages/storage-events/src/replay.spec.js
Adds the option to edit a todo title when clicking on it and submitting it via <enter>.
It does NOT signal editing to other users nor send an event for it (yet)
> Edit todos

- packages/server-web/src/client/components/TodoItem.vue
- packages/storage-events/src/event.js
- packages/storage-events/src/event.spec.js
> Add status toggling.

- packages/server-web/package.json
- packages/server-web/src/client/component/Home.vue
- packages/server-web/src/client/component/Repl.vue
- packages/server-web/src/client/components/Repl.vue
Add a little scripting zone that has access to all todos.
> Scripting power

- packages/server-web/src/client/component/TodoItem.vue
> Make dropzone clickable (fix #65)

- packages/server-web/src/client/component/TodoItem.vue
> Fix scaling of done todos

- packages/server-web/src/client/component/TodoItem.vue
- ~[ ] installs new dependencies through `npm run bootstrap`~
- ~[ ] contains a breaking change~
**Changes**
Removes the upper dropzone.
> remove upper dropzone in todo items. fix #80

- packages/server-web/src/client/component/TodoText.vue
- ~contains a breaking change~
**Changes**
- Adds a few more todo-ideas.
> Add more todo-ideas

- .github/PULL_REQUEST_TEMPLATE.md
- ~[ ] resolves #<issue-id>~
- ~[ ] installs new dependencies through `npm run bootstrap`~
- ~[ ] contains a breaking change~
**Changes**
- Add changelog to pull request
> Start using changelog

- packages/server-web/src/client/component/Login.vue
- ~contains a breaking change, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
- ~contains a new feature, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
**Changes**
- Add logo to login page
> Add logo to login page

- packages/server-web/src/client/component/Help.vue
- ~contains a breaking change, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
- ~contains a new feature, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
**Changes**
- Fix documentation
> Fix syntax error in documentation for #TRACK

- packages/konsol/src/user-add.js
…works
- ~resolves #<issue-id>~
- ~contains a breaking change, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
- ~contains a new feature, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
**Changes**
> Add more awaits and asyncs in the mix of the new user script

- packages/server-web/src/client/component/TodoText.vue
- ~contains a breaking change, which is documented in the [changelog](../blob/master/CHANGELOG.md)
- ~contains a new feature, which is documented in the [changelog](../blob/master/CHANGELOG.md)~
**Changes**
- Prevent creating empty todos
> fix #102 - prevent empty todos

- packages/server-socket/src/__snapshots__/command-processor.spec.js.snap
- packages/server-socket/src/command-processor.js
- packages/server-web/src/lib/__snapshots__/details-extractor.spec.js.snap
- packages/server-web/src/lib/__snapshots__/label-extractor.spec.js.snap
- packages/server-web/src/lib/__snapshots__/tracked-time-extractor.spec.js.snap
- packages/server-web/src/lib/details-extractor.spec.js
- packages/server-web/src/lib/label-extractor.js
- packages/server-web/src/lib/tracked-time-extractor.js
- packages/storage-mongo/src/lib/event.js
- ~contains a breaking change~
- ~contains a new feature~
**Changes**
- Makes sure, we don't get any empty arrays from mongoose where they shouldn't be
> fix #117 - tracked times should not disappear when setting todo to done

- .travis.yml
- README.md
- docker-compose.yml
- package-lock.json
- package.json
- ~resolves #<issue-id>~
- ~contains a breaking change~
- ~contains a new feature~
**Changes**
- Installs the coveralls lib and sends the coverage there
> replace codeclimate coverage by coveralls

- packages/server-web/src/client/component/Login.vue
- packages/server-web/src/client/component/Profile.vue
- packages/server-web/src/client/component/TodoOptions.vue
- packages/server-web/src/client/create-store.js
- ~resolves #<issue-id>~
- ~contains a breaking change~
- ~contains a new feature~
**Changes**
- switches trash and plus button so that double clicking doesn't accidentally remove todos
- shows the username in UI
> switch trash and plus button / add username to profile button
